name: Windows Cloud RDP

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty `
            -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" `
            -Name "fDenyTSConnections" -Value 0

          Set-Service -Name TermService -StartupType Automatic
          Start-Service -Name TermService

          New-NetFirewallRule `
            -DisplayName "Allow RDP 3389" `
            -Direction Inbound `
            -Protocol TCP `
            -LocalPort 3389 `
            -Action Allow `
            -ErrorAction SilentlyContinue

      - name: Create RDP User
        shell: powershell
        run: |
          $Password = ConvertTo-SecureString "ChangeMe_7392!Ab" -AsPlainText -Force

          New-LocalUser `
            -Name "NvdAdmin" `
            -Password $Password `
            -PasswordNeverExpires `
            -ErrorAction SilentlyContinue

          Add-LocalGroupMember `
            -Group "Administrators" `
            -Member "NvdAdmin" `
            -ErrorAction SilentlyContinue

      - name: Install Tailscale
        shell: powershell
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          Invoke-WebRequest `
            "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" `
            -OutFile "C:\tailscale.msi"

          Start-Process msiexec.exe `
            -ArgumentList "/i C:\tailscale.msi /quiet /norestart" `
            -Wait

          Start-Sleep -Seconds 10

          & "C:\Program Files\Tailscale\tailscale.exe" up `
            --authkey="$env:TAILSCALE_AUTHKEY" `
            --hostname="github-rdp-server"

          Start-Sleep -Seconds 10

          $ip = & "C:\Program Files\Tailscale\tailscale.exe" ip -4

          Write-Host "=============================="
          Write-Host "RDP READY"
          Write-Host "IP: $ip"
          Write-Host "Username: NvdAdmin"
          Write-Host "=============================="

          Test-NetConnection 127.0.0.1 -Port 3389

      - name: Keep Alive
        shell: powershell
        run: |
          for ($i = 1; $i -le 350; $i++) {
            Start-Sleep -Seconds 60
            Write-Host "Server running: $i minutes"
          }
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "NvdAdmin" -ErrorAction SilentlyContinue
